### ISSUE TITLE
Can not import project to android studio

### ISSUE THREAD

**Issue by sagarnayak** [GautamGupta/Simple-Android-OCR#11]
* Project Simple-Android-OCR:D:\AS_Projects\Simple-Android-OCR-master\project.properties:
Library reference ..\tess-two could not be found
Path is D:\AS_Projects\Simple-Android-OCR-master\..\tess-two which resolves to D:\AS_Projects\tess-two

**Comment by GautamGupta** [comment]
It's not meant to be, sorry. Please follow these instructions for Android Studio: http://gaut.am/making-an-ocr-android-app-using-tesseract/#comment-184181
