### ISSUE TITLE
error: package com.googlecode.tesseract.android does not exist

### ISSUE THREAD

**Issue by AbhirojPanwar** [GautamGupta/Simple-Android-OCR#13]
Hi,

I am trying to build the android application on Android Studio. The thing is in your blog you have about using ndk-build , ant and using Eclipse as IDE, I wonder what are the alternatives for windows users using Android Studio. I have my Android Studio setup on windows, have cloned tess-two from rmtheis also in the same directory.  But whenever  I am trying to run the app, it says this error :- package com.googlecode.tesseract.android does not exist. I wonder what can be the solution to the problem.

**Comment by GautamGupta** [comment]
Hey. Check this [comment](http://gaut.am/making-an-ocr-android-app-using-tesseract/#comment-184181).
