### ISSUE TITLE
How to add support to read micr code ?

### ISSUE THREAD

**Issue by kirantpatil** [GautamGupta/Simple-Android-OCR#14]
Hi,

I would like to add code to read micr from check as mentioned below.

https://stackoverflow.com/questions/25279271/android-how-to-recognize-micr-codes

Please let me know where to modify code and how to add mcr.traineddata to this project.

Thanks.

**Comment by EricLee3** [comment]
Hi, 

I have no idea what I have done to this project. 
I just forked and compiled it to test OCR a while ago. 

By that, I recognized the result was not enough to my OCR project and I didn't add (or trained) new mcr.traineddata. 

Sorry for not helping out.

**Comment by kirantpatil** [comment]
Closing this, since the app code straight forward to  understand and make modification.
