### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by SLieve** [GautamGupta/Simple-Android-OCR#6]
Downloaded the project, followed the instructions at http://gaut.am/making-an-ocr-android-app-using-tesseract/

But I am getting this error: 

```
03-09 21:49:57.368: E/AndroidRuntime(27702): java.lang.UnsatisfiedLinkError: Couldn't load lept from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.datumdroid.android.ocr.simple-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.datumdroid.android.ocr.simple-2, /vendor/lib, /system/lib]]]: findLibrary returned null
```

This happens here:

```
03-09 21:49:57.368: E/AndroidRuntime(27702):    at com.datumdroid.android.ocr.simple.SimpleAndroidOCRActivity.onPhotoTaken(SimpleAndroidOCRActivity.java:211)
```

Which is this code:

```
TessBaseAPI baseApi = new TessBaseAPI();
```

I have searched, and this is the corresponding issue in the tess-two project:
https://github.com/rmtheis/tess-two/issues/34
Which says to use the same android build target in the tess-two library as the project that's using it. But I am doing that.
![capture](https://f.cloud.github.com/assets/3666512/2370376/cee9fe54-a802-11e3-812e-2f839ff9a730.PNG)
![capture1](https://f.cloud.github.com/assets/3666512/2370377/cef03c10-a802-11e3-846d-56dc406f13bc.PNG)

**Comment by mmelchio** [comment]
Thanks for your post, SLieve, you saved me..
